export class VideoRequestCode {
  /*************video接口开始**************/
  public static readonly VIDEO_DESCRIBE_DEVICES = 20000
  public static readonly VIDEO_DESCRIBE_DATE = 20001
  public static readonly VIDEO_DESCRIBE_DATE_TIME = 20002
  public static readonly VIDEO_DESCRIBE_URL = 20003
  public static readonly VIDEO_DESCRIBE_RECORD_DATE = 20004
  public static readonly VIDEO_DESCRIBE_SNAPSHOT = 20005
  public static readonly VIDEO_DESCRIBE_VIDEO_URL = 20006
  public static readonly VIDEO_DESCRIBE_PRODUCT = 20007
  /*************video接口结束**************/
}